export const physicochemicalPropertyList = [
  //   "SMILES",
  //   "prob_TARGET",
  //   "prob_TARGET_1",
  //   "prob_TARGET_2",
  //   "predict_TARGET",
  //   "predict_TARGET_1",
  //   "predict_TARGET_2",
  "MW",
  "nHA",
  "nHD",
  "nHet",
  "nRigid",
  "nRot",
  "nRing",
  "MaxRing",
  "TotalCharge",
  "Flexibility",
  "nStereoCenters",
  "TPSA",
  // "MW",
  // "nHA",
  // "nHD",
  // "nRot",
  // "nRing",
  // "MaxRing",
  // "nHet",
  // "TotalCharge",
  // "nRigid",
  // "Flexibility",
  // "nStereoCenters",
  // "TPSA",
];
